### ISSUE TITLE
why does vertex_triangle_adjacency produce TT with rows that have more than 3 entries?

### ISSUE THREAD

**Issue by oveddan** [danielepanozzo/gp-old#12]
vertex_triangle_adjacency [documentation](https://github.com/libigl/libigl/blob/5da97504fbc9c44e1a7396fff0373d16f69fa149/include/igl/triangle_triangle_adjacency.h#L27)

Says that:
"TT   #F by #3 adjacent matrix, the element i,j is the id of the triangle adjacent to the j edge of triangle i"

However, when running the following code for `cylinder_coarse.off`:

```
igl::vertex_triangle_adjacency(V, F, VF, VFi);
 for (unsigned int i=0; i < VF.size(); i++) {
    for (unsigned int j = 0; j < VF[i].size(); j++) {
      cout << VF[i][j] << " ";
    }

    cout << endl;
  }
```

I get output like:
```
0 39 79 
0 1 40 
1 2 41 
2 3 42 
3 4 43 
4 5 44 
5 6 45 
6 7 46 
7 8 47 
8 9 48 
9 10 49 
10 11 50 
11 12 51 
12 13 52 
13 14 53 
14 15 54 
15 16 55 
16 17 56 
17 18 57 
18 19 58 
19 20 59 
20 21 60 
21 22 61 
22 23 62 
23 24 63 
24 25 64 
25 26 65 
26 27 66 
27 28 67 
28 29 68 
29 30 69 
30 31 70 
31 32 71 
32 33 72 
33 34 73 
34 35 74 
35 36 75 
36 37 76 
37 38 77 
38 39 78 
0 40 79 80 120 159 
1 40 41 81 120 121 
2 41 42 82 121 122 
```

Some rows have more than 3 entries.  How could this be possible if triangles would only have up to three neighbors?

Is this the method we are supposed to use to get the `Adjacency TT`?

**Comment by jpanetta** [comment]
The documentation you link to is for the correct function, triangle_triangle_adjacency, but you're calling the incorrect function vertex_triangle_adjacency.

**Comment by oveddan** [comment]
Thank you :)
