### ISSUE TITLE
Question on Assignment 4

### ISSUE THREAD

**Issue by WDYBQJ** [danielepanozzo/gp-old#16]
In part 3, you said,

> Compute the gradient of the selected mapping function and overlay it (key ’6’).

What does it mean? In my mind, gradient is a vector. But your figure 3b shows a colormap. Could you please make a further explanation?

**Comment by jpanetta** [comment]
If you zoom in, you should be able to see the gradient vector field plotted with gray line segments over the v scalar fieldl's colormap. You could probably choose colors that make the vectors more obvious.
