### ISSUE TITLE
Couple of questions about Assignment 2

### ISSUE THREAD

**Issue by abhijit-c** [danielepanozzo/gp-old#28]
Hello all,

I had a few questions about Assignment 2, specifically regarding our assignment. Also I don't know if there's a nice way to do inline math in github issues, but it wasn't coming out good so I stuck to what seemed readable.

1. Basically about MLS:
- When we think about matrix B (in terms of the recitation slides) we are defining Bij = bj(ci) where ci refers to the i'th constraint we have created. I don't quite understand what is being referenced by the j'th basis function. We are working with the polynomial basis function of degree less than 2, so something along the lines of f(u) = c0 + c1u  + c2u^2. So then (since we are in R^3) if I choose degree = 1 then would my matrix be 4x4 i.e. the first row of B would look like: [1 x1 y1 z1] where c1 = (x1,y1,z1)? 
- We are defining some wendlandRadius relative to the size of the mesh, and then we are defining our distance function w to make sure that any distance greater than the wendlandRadius will evaluate to zero. So then we can make queries such as ask for all points that land in the open ball centered around point x with wendlandRadius to get the set of points we are most concerned about to influence the construction of f. In the recitation slides, the matrix W whose i'th diagonal is defined to have the value w(||x-ci||) is said to have size  3N x 3N. But a vast majority of the points in our 3N point set do not land in our open ball, thus the evaluation of w(||x-ci||) for these ci will just be zero. So then the question is when considering the implicit function evaluation at point x, why don't we restrict our constraint set to this open ball and instead define W to only consider the constraints in this new set?

2. About 2.1 (Create a grid sampling the 3D space). Why is what is written in the example grid construction in createGrid insufficient? To me it seems that no matter what we will just be constructing a grid in the same manner, looking at the max/min areas and partitioning them according to the resolution. What functionality were we to implement?

3. Regarding the spatial index we are creating. I've a couple of ideas on how to implement this, none that don't require building up some underlying k-d structure. Basically I'm trying to implement how Matlab does their rangesearch function, which I think under certain criterion they implement a k-d structure under the hood. Is there anything in libigl / Eigen that would help with this, or am I implementing this from scratch? Actually now that I'm thinking about this more, we might be able to something like instead rounding each coordinate down to an integer multiple of the wendlandRadius and afterwards just searching the lattice points around my point x to see if there exist any points that got mapped onto those.

**Comment by jiangzhongshi** [comment]
>
>    Basically about MLS:
>
>
>    - When we think about matrix B (in terms of the recitation slides) we
>    are defining Bij = bj(ci) where ci refers to the i'th constraint we have
>    created. I don't quite understand what is being referenced by the j'th
>    basis function. We are working with the polynomial basis function of degree
>    less than 2, so something along the lines of f(u) = c0 + c1u + c2u^2. So
>    then (since we are in R^3) if I choose degree = 1 then would my matrix be
>    4x4 i.e. the first row of B would look like: [1 x1 y1 z1] where c1 =
>    (x1,y1,z1)?
>
>
MLS is an algorithm that infers a surface from a few points, with the prior
that this surface is represented by a combination of basis functions. In
this case, four basis are [1, X(p), Y(p), Z(p)], and you have several
constraint points p1 p2...pk as input. So this is bi( 4 basis)and cj (k
points)

>
>    - We are defining some wendlandRadius relative to the size of the
>    mesh, and then we are defining our distance function w to make sure that
>    any distance greater than the wendlandRadius will evaluate to zero. So then
>    we can make queries such as ask for all points that land in the open ball
>    centered around point x with wendlandRadius to get the set of points we are
>    most concerned about to influence the construction of f. In the recitation
>    slides, the matrix W whose i'th diagonal is defined to have the value
>    w(||x-ci||) is said to have size 3N x 3N. But a vast majority of the points
>    in our 3N point set do not land in our open ball, thus the evaluation of
>    w(||x-ci||) for these ci will just be zero. So then the question is when
>    considering the implicit function evaluation at point x, why don't we
>    restrict our constraint set to this open ball and instead define W to only
>    consider the constraints in this new set?
>
>
It’s equivalent, if you are not defining them at all, or set them as zero.
And doesn’t affect performance for sparse matrices. You can of course use a
smaller W, but in our way the formulation looks simpler and more uniform.

>    About 2.1 (Create a grid sampling the 3D space). Why is what is
>    written in the example grid construction in createGrid insufficient? To me
>    it seems that no matter what we will just be constructing a grid in the
>    same manner, looking at the max/min areas and partitioning them according
>    to the resolution. What functionality were we to implement?
>
>
It is similar, but there is slight difference to modify: including computing bounding box, expose resolution to UI, and do a proper ordering when storing them.


>    Regarding the spatial index we are creating. I've a couple of ideas
>    on how to implement this, none that don't require building up some
>    underlying k-d structure. Basically I'm trying to implement how Matlab does
>    their rangesearch function, which I think under certain criterion they
>    implement a k-d structure under the hood. Is there anything in libigl /
>    Eigen that would help with this, or am I implementing this from scratch?
>

As far as I am concerned, any kind of simplication approach, that doesn’t
require a traverse each time, is acceptable.—

**Comment by abhijit-c** [comment]
Yes thanks a lot, that cleared up my difficulties with MLS and I see what's problematic with the example code now! 

I will think more on a better implementation for the spatial index.

Much appreciated!
