### ISSUE TITLE
Travis build error

### ISSUE THREAD

**Issue by darkpursuer** [danielepanozzo/gp-old#29]
There was always an error when building on the Travi. And here's the log:

CMake Error at CMakeLists.txt:44 (add_executable):
  Target "ex2_bin" links to target "igl::viewer" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

/home/travis/build/NYUGeometricModeling/gm-assignment-2-darkpursuer/src/main.cpp:2:31: fatal error: igl/viewer/Viewer.h: No such file or directory
 #include <igl/viewer/Viewer.h>
                               ^

What should I do to go through it?

**Comment by jiangzhongshi** [comment]
Hi,

Please update the .travis file to https://github.com/NYUGeometricModeling/GM_Assignment_2/blob/master/.travis.yml

This is due to a refactor in libigl that broke backward compatibility.

Best,
Zhongshi

**Comment by darkpursuer** [comment]
Hi Zhongshi,

Thanks for your advice, the error has been solved.
