### ISSUE TITLE
Checking if pi+N is the closest point

### ISSUE THREAD

**Issue by oveddan** [danielepanozzo/gp-old#3]
In the homework assignment it is instructed to `Check that pi is the closest point to pi+N;`  By this do you mean check if any other points are closer to `pi+N` than `pi` is?  To do this should we do a brute force search over all existing points, or is there a better way?  Should this search for closer points include constraint points?

**Comment by jpanetta** [comment]
Yes, you are supposed to ensure that the point you create by offsetting along the normal from p_i remains closer to p_i than to any other input point. You can initially implement this with a brute-force loop, but problem 1.2 asks you to create a data structure to accelerate the query.

You should consider only the original cloud points in this search. For example, if the original point cloud is planar, we want to create two parallel planes of offset points at (+/- epsilon). If you were to consider the previously-created offset points in your closest point check, and if the input points are spaced more closely than epsilon in the plane, you would get jagged offset surfaces.

**Comment by oveddan** [comment]
Thank you that is very helpful.  I'll make sure to create the data structure first before executing this search.
