### ISSUE TITLE
Could TA provide an optimized model files with denser points?

### ISSUE THREAD

**Issue by darkpursuer** [danielepanozzo/gp-old#30]
Hi Zhongshi,

Could you please provide an optimized model files with denser points, which are refined by MeshLab?

**Comment by jiangzhongshi** [comment]
Hi,

I added a few models here. https://github.com/NYUGeometricModeling/GM_Assignment_2/commit/a64665591f8b3332698f80914801e88ece931c0b

They are easily created by [MeshLab](http://www.meshlab.net/)
You can try them out if you like.

Best,
Zhongshi

**Comment by darkpursuer** [comment]
Hi Zhongshi,

Thanks for your help.
