### ISSUE TITLE
What are "hard constraints"?

### ISSUE THREAD

**Issue by majia67** [danielepanozzo/gp-old#31]
I'm working on Assignment 4 and on lecture slide 7, page 58, the professors mentions we need to implement hard constraints instead of soft ones. Could you further explain what are "hard constraints"?

**Comment by jiangzhongshi** [comment]
Hard constraints means that the given condition has to be satisfied
exactly, in contrast to soft constraints which only penalize if you
violate, but does not guarantee satisfaction.

**Comment by majia67** [comment]
Then how do we ensure the given condition is satisfied exactly? I think currently we use a big lambda.

**Comment by jiangzhongshi** [comment]
Yes, the solution to the big lambda won't guarantee the result in this
case. So you are basically solving for a constrained optimization problem,
for specifics, you can refer to the last slides here
https://cs.nyu.edu/~panozzo/gp18/Assignment4.pdf

**Comment by majia67** [comment]
Do you mean using the “Variable Elimination” method mentioned in the slide?

**Comment by jiangzhongshi** [comment]
Yes that’s correct

**Comment by majia67** [comment]
Thank you!

**Comment by majia67** [comment]
I'm wondering if the "Variable Elimination" method is only used in the second part of the assignment? According to the slides, "Variable Elimination" is used for reconstructing a scalar field, not a vector field. @jiangzhongshi @danielepanozzo

**Comment by danielepanozzo** [comment]
You need to use the variable elimination method also for implementing the hard constraints for the vector field interpolation. (As an alternative, you can use Lagrange multipliers, but it is harder to implement and slower, so I don't recommend to go that way).

**Comment by majia67** [comment]
Thanks!
