### ISSUE TITLE
Question About Parametrization

### ISSUE THREAD

**Issue by majia67** [danielepanozzo/gp-old#32]
On lecture slide 8 (Single Patch Parametrization), page 96, it says "Designing a parametrization is equivalent to designing two scalar functions". Could you further explain why these two are equivalent?

**Comment by jiangzhongshi** [comment]
A parameterization is assigning (u,v) to each of the points p on the surface, you can imagine it as design two scalar functions u(p) and v(p).

**Comment by majia67** [comment]
Thank you!
