### ISSUE TITLE
Point Cloud =?> Surface

### ISSUE THREAD

**Issue by abhijit-c** [danielepanozzo/gp-old#35]
Hello,

I was wondering if libigl had a way to directly take a point cloud with normals to reconstructed surface / mesh. I realize I can re-implement what we did in Assignment 2, but I'm looking for an tested and proven reconstruction method in libigl to compare what my paper implements with. Maybe I could get a recommendation of a reconstruction algorithm to compare the algebraic point set surfaces method to?

**Comment by danielepanozzo** [comment]
Hi,

libigl does not have any built-in surface reconstruction method yet. I suggest you compare with http://www.cs.utah.edu/~bergerm/recon_bench/ , they provide directly the input/output of many methods.

Daniele

**Comment by abhijit-c** [comment]
I see. That website is extremely helpful though, much appreciated.
