### ISSUE TITLE
multiple meshes in libigl viewer

### ISSUE THREAD

**Issue by bmahlbrand** [danielepanozzo/gp-old#36]
I've looked at https://github.com/libigl/libigl/blob/master/tutorial/107_MultipleMeshes/main.cpp

But is there a basic example for appending multiple meshes on top of the main mesh I've already read in from a file?  Say I wish to render patches of faces on top, or a plane?  I suppose I could just append the main V, F matrices (not a big deal) but curious if there's something cleaner.

**Comment by jiangzhongshi** [comment]
Hi,

Tutorial used `load_mesh_from_file` function, which you can have a look at the code here https://github.com/libigl/libigl/blob/master/include/igl/opengl/glfw/Viewer.cpp# to get a sense of what's going on.

Basically, you can replace the loop in the tutorial with something like this.
```
  for(const auto & name : names)
  {
    Eigen::MatrixXd V;
    Eigen::MatrixXi F;
    viewer.append_mesh();
    igl::readOBJ(std::string(TUTORIAL_SHARED_PATH) + "/" + name, V, F);
    viewer.data().set_mesh(V,F);
    colors.emplace(viewer.data().id, 0.5*Eigen::RowVector3d::Random().array() + 0.5);
  }
```
where `data()` refers to the most recent one.

**Comment by bmahlbrand** [comment]
Ah okay, I see how it works now, thanks!
