### ISSUE TITLE
How to disable keyboard callbacks while interacting with menu

### ISSUE THREAD

**Issue by bmahlbrand** [danielepanozzo/gp-old#40]
Basically I have some InputFloats / InputInt, and wish to use them while temporarily disabling the callbacks triggering. Is there an easy way to do that?

**Comment by abhijit-c** [comment]
jdumas commented with this [link (libigl bug #764)](https://github.com/libigl/libigl/issues/764) when I asked a similar question. I found his response helpful in dealing with the bug (although personally I just changed over to sliders)

**Comment by bmahlbrand** [comment]
Ah, nice catch, thanks! Yeah I'm not going to spend any more time messing with it - just convenient since I may or may not have a good range of values set in the sliders.

**Comment by abhijit-c** [comment]
Alternatively instead of waiting for a key down you could instead build buttons into imgui to run the necessary operations. Actually I might do that myself, that might be the easiest depending on how strange buttons are in imgui.
