### ISSUE TITLE
HW1: how to tell CMAKE the path of libigl(i.e. LIBIGL_INCLUDE_DIR)

### ISSUE THREAD

**Issue by LihengGong** [danielepanozzo/gp-old#42]
I can see from CMakeLists.txt in assignment 1 that `libigl` is automatically downloaded by the script, but the problem is that `LIBIGL_INCLUDE_DIR` is not explicitly set.

My question is: should we set it manually ourselves or should we set it by modifying the CMAKE file?

Thanks

**Comment by danielepanozzo** [comment]
Both options are fine. I recommend the former, since it will then work for all assignments without having to modify the individual cmake files.

**Comment by LihengGong** [comment]
Thanks prof. Have a nice weekend.
