### ISSUE TITLE
libigl viewer: how to make the menu visible?

### ISSUE THREAD

**Issue by LihengGong** [danielepanozzo/gp-old#43]
I can see from the tutorial that there is a menu in the left side pane of libigl viewer(for example Example 102), but I just built the code of assignment1 and found that there is no such menu for my viewer.

My question is: Do I need to toggle any configurations to make the menu visible?

Thanks

**Comment by danielepanozzo** [comment]
The bar is not needed for the assignments, but if you want to turn it on you should do the following changes:
1. Add to the cmakelist: 
``option(LIBIGL_WITH_OPENGL_GLFW_IMGUI "Use ImGui"         ON)``
2. Add the include to your main.cpp
``#include <igl/opengl/glfw/imgui/ImGuiMenu.h>``
3. Add the bar to the viewer in your main.cpp
`` 
igl::opengl::glfw::imgui::ImGuiMenu menu;
viewer.plugins.push_back(&menu);
``
4. Delete your cmakecache and rebuild.

If you want to edit the bar or add your own (which is very useful for debugging), take a look at this tutorial: https://libigl.github.io/tutorial/#viewer-menu

**Comment by LihengGong** [comment]
Thanks prof. That's very helpful.
Have a good night.

**Comment by txstc55** [comment]
In target_link_libraries also need to add:
igl::opengl_glfw_imgui
