### ISSUE TITLE
Homework2 "halve the epsilon"

### ISSUE THREAD

**Issue by potato1996** [danielepanozzo/gp-old#46]
Hi Prof and TA,

I'm almost finishing question 1.1 and 1.2 and now I'm working on automatically adjust the "epsilon". 

The instruction says "Check that pi is the closest point to pi+N; if not, halve epsilon and recompute pi+N until this is the case". So after I halve the epsilon, should I re-compute all the constrain points (even if they satisfied the requirement with the original epsilon), or I just need to decrease the epsilon for this specific point? 

In another word, should I make sure that every point have the same epsilon? I think doing so might possibly make the surface more "smooth", but the instruction sounds like I just need to decrease the epsilon for this point. 

Thank you!

**Comment by danielepanozzo** [comment]
It is not necessary to use the same epsilon to generate the points for the additional constraints, you can use a fixed epsilon for most of the points, and decrease it only for the ones where the condition "pi is the closest point to pi+N" does not hold.

**Comment by potato1996** [comment]
> It is not necessary to use the same epsilon to generate the points for the additional constraints, you can use a fixed epsilon for most of the points, and decrease it only for the ones where the condition "pi is the closest point to pi+N" does not hold.

Thank you!
