### ISSUE TITLE
[Assignment 2] Is normals already provided in *.off file?

### ISSUE THREAD

**Issue by LihengGong** [danielepanozzo/gp-old#47]
I can see that in most of the *off files provided in `/data` directory, there are 6 data items each line and I assume `igl::readOFF(argv[1],P,F,N);` loads point coordinates and normal coordinates into matrices `P` and `N`.

My question is:

Regarding the program, can I assume that `P` is point coordinates and `N` is normal for that point and I can use them directly as the input?

```C++
// Input: imported points, #P x3
Eigen::MatrixXd P;

// Input: imported normals, #P x3
Eigen::MatrixXd N;
```

**Comment by danielepanozzo** [comment]
Yes that's correct.

**Comment by LihengGong** [comment]
Thanks prof. Have a nice day.
