### ISSUE TITLE
[Assignment 2] Calculating the coefficient a(x) of MLS function

### ISSUE THREAD

**Issue by greenson** [danielepanozzo/gp-old#48]
I have been stuck on this issue for several days. 

From what I have learnt in the recitation lecture (slide page 15), `a(x)` is the only unknown element in the equation of `(B^T*W(x)*B)*a(x) = B^T*W(x)*d` since all `B`, `W(x)` and `d` are given or can be computed from the existing elements we have. My question is, what should we do if `W(x)` is a zero set: in this case, both sides of the above equation are zero, which leads to no solution of the vector `a(x)`. 

Thank you!

**Comment by danielepanozzo** [comment]
I am not sure of what you mean by "zero set": are you asking about what to do when there are no points (or too few) within the distance threshold that you set, and thus you get a linear system is underdetermined? In this case, the recommendation is to simply return a very high value. This is briefly described in the assignment notes: "If no constraint points are within wendlandRadius of the evaluation grid point, you can assign a large positive (outside) value to the grid point."
