### ISSUE TITLE
[Assignment 2] Optional Task 1

### ISSUE THREAD

**Issue by potato1996** [danielepanozzo/gp-old#49]
Hi Prof. and TA,

Would you mind emphasize a little bit about what Optional Task 1 requires us to do ? (i.e. "Compute the closed-form gradient of the MLS approximation"). In my understanding MLS sounds more like a "method", so I'm a little bit confused that in this question we should give out the gradient of what on what? Besides, what is required to present the result for this task?

Thank you!

**Comment by danielepanozzo** [comment]
MLS is a way of interpolating scalar values defined on a sparse set of points. We use it in the class to interpolate a distance field whose 0 level set corresponds to the surface we are trying to compute. The optional task asks you to compute the gradient of the scalar field obtained using MLS.
