### ISSUE TITLE
[Assignment 2] MLS very slow(2 minutes to compute bunny_500) even if release mode is used

### ISSUE THREAD

**Issue by LihengGong** [danielepanozzo/gp-old#51]
Dear professor,

Sorry for this last minute question.
I found that my program runs extremely slow even in release mode. It takes about 2 or 3 minutes to process and draw the simplest bunny-500.off.

I'm not sure if this is normal or not. Thank you

Thank you
Liheng

**Comment by danielepanozzo** [comment]
A couple of minutes is a reasonable running time. You can use igl::Timer to figure out where it is spent, if it is spent solving the linear system for MLS then it is normal. If it is spent in the data structure to find the neighbors, it is probably possible to improve performances by making the spatial index grid denser.

**Comment by LihengGong** [comment]
Thank you professor; that's very helpful.

Have a good night.
