### ISSUE TITLE
[Assignment 2] Thoughts about 2.3

### ISSUE THREAD

**Issue by LihengGong** [danielepanozzo/gp-old#52]
Regarding `2.3. Using a non-axis-aligned grid`, the scenario I can think of is a long thin stick placed from the left lower corner to the right upper corner in a box so that lots of space is wasted. If we can align the axis so that the stick is "erected" or "lay down", space will not be wasted.

My question is: Are my thoughts in the right direction? Thank you.

**Comment by potato1996** [comment]
Yeah I think so. And as pointed out [here](https://github.com/NYUGraphics/GM_Assignment_2/issues/1) PCA can give us a rough approximation :)

**Comment by LihengGong** [comment]
> Yeah I think so. And as pointed out [here](https://github.com/NYUGraphics/GM_Assignment_2/issues/1) PCA can give us a rough approximation :)

Awesome!
