### ISSUE TITLE
[Assignment 2] Can we specify value of "h" for each particular model?

### ISSUE THREAD

**Issue by yuepingwang** [danielepanozzo/gp-old#53]
Hi Professor and TA, 

Are we allowed to explicitly set the h value for each of different .off models? Or do we need to create a way of calculating the value of h (based on density etc.) that works well for any .off models given in the assignment?

Thank you!

**Comment by danielepanozzo** [comment]
Yes you can set a different h for each model.

**Comment by yuepingwang** [comment]
Thank you!
