### ISSUE TITLE
[Assignment 2] Shall we process meshes without normals such as bunny_2k.off?

### ISSUE THREAD

**Issue by LihengGong** [danielepanozzo/gp-old#54]
Just curious, shall we process the meshes without normals such as bunny_2k.off?

Thanks

**Comment by jiangzhongshi** [comment]
It's not necessary, but you can use normal estimation techniques. Or simply `igl::per_vertex_normals`

**Comment by LihengGong** [comment]
Thanks. The advice and the API are very helpful.
