### ISSUE TITLE
smoothing by sampling and interpolation

### ISSUE THREAD

**Issue by josherich** [danielepanozzo/gp-old#55]
I can imagine a way of smoothing that, first do sampling on mesh surface, and interpolate using either global method or local method we have on hand, this could be done iteratively. details can be taken care of with sampling method and density. do you think it's a valid idea, anyone tried this one?

**Comment by danielepanozzo** [comment]
Yes absolutely, it is possible to smooth by resampling the surface. We are going to cover this a bit later in the class after we will study parametrization. You can take a look at the remeshing and simplification chapters of the textbook http://www.pmp-book.org.
