### ISSUE TITLE
[Assignment 4] How to understand a "hat" function and how to take gradient on that?

### ISSUE THREAD

**Issue by potato1996** [danielepanozzo/gp-old#57]
Hi Prof. and TA,

I think I'm getting a little bit lost on understanding the hat functions in Assignment 4 Section 2.. 

The assignment advice us to use a hat function for each triangle vertex. So the hat function should take a 3-d coordinate **x** as input, returns 1 or 0, and there's a different hat function for each vertex in the mesh? If so how to take the gradient on these hat functions? Why only s_i are unknowns but not the parameters inside the "hat functions"?

Thank you!

**Comment by danielepanozzo** [comment]
I suggest to discuss this in person tomorrow during my office hour, it is much easier to explain with a whiteboard.

**Comment by potato1996** [comment]
Question solved after the class yesterday. Thanks!
