### ISSUE TITLE
[Assignment 4] Question about Eigen Sparse Matrix

### ISSUE THREAD

**Issue by yuepingwang** [danielepanozzo/gp-old#58]
Hi!
I was a little confused when reading the Eigen documentation on sparse matrices:
https://eigen.tuxfamily.org/dox/group__TutorialSparse.html

<img width="829" alt="Screen Shot 2019-03-27 at 11 52 38 PM" src="https://user-images.githubusercontent.com/15027748/55129129-68aa3580-50ec-11e9-8f3b-f1441804f313.png">

In "Values",  it seems that "14" should be in a separate column than "3 5"?
And would you mind explaining how the "OuterStarts" is counted in this example?

Thank you!

**Comment by danielepanozzo** [comment]
The example seems correct to me, the 3rd column has outer start of 5, which is the 6th entry of values, adding the value 14 in the 5th row. The "_" are simply unused slots that are "wasted" in this representation. I will go over this in the class today. As a general rule, it is a bad idea to directly try to use this low level representation for sparse matrices, you can directly use the triplets to create your sparse matrices: https://eigen.tuxfamily.org/dox/group__TutorialSparse.html#TutorialSparseFilling

**Comment by yuepingwang** [comment]
Thank you!
