### ISSUE TITLE
[Logistics: HW late policy] May I know the late policy of our homework? 

### ISSUE THREAD

**Issue by LihengGong** [danielepanozzo/gp-old#59]
Dear Professor,

Sorry for such an embarrassing question but I feel that I cannot solve HW4 before April 3rd(yeah I know it is totally my fault and I only blame myself). So may I know the late policy of HW assignment?
Sorry again and thanks for your patience.

Thanks

**Comment by toxicaker** [comment]
So do I....

Dear professor,

Could you please delay the deadline a little bit. 
Hw4 is pretty difficult for me because of my poor math.

Thanks

**Comment by greenson** [comment]
Maybe I was the only one who thought the deadline was **Apr 11** 2018 indicated in the hw4 repo 😥

**Comment by yichangC** [comment]
> Maybe I was the only one who thought the deadline was **Apr 11** 2018 indicated in the hw4 repo 😥

You're not the only one...

**Comment by bambrow** [comment]
> Maybe I was the only one who thought the deadline was **Apr 11** 2018 indicated in the hw4 repo 😥

Same here...

**Comment by danielepanozzo** [comment]
I forgot to update the date in the hw4 repo, sorry for the unnecessary confusion. Given that some of you planned the assignment using the wrong deadline, I decided to grant an extension for the assignment to everyone: the new deadline is *Apr 10, 2019 at 23:59EST*.

As usual, please do take advantage of my office hour and the office our of Zhongshi if you have questions or if you need help.

**Comment by LihengGong** [comment]
Thanks prof. You're like the sunshine this afternoon.

Have a nice weekend.

Thanks and regards
Liheng
