### ISSUE TITLE
Review of pseudocode/question on MLS Approximation

### ISSUE THREAD

**Issue by oveddan** [danielepanozzo/gp-old#6]
For MLS Approximation, are the steps to:

1. Setup a set of linear equations, only using constraints within a radius of a point X.
This set of linear equations is essentially:
A * B * c = d
Where `A` is a symmetrical matrix containing the Wendland function applied to the squared differences of a constraint (`cj`) with all of the other constraints (`ci...n`)
`B` is a symmetrical matrix containing the squared differences of the constraint (cj) with all the other constraints (`ci...n`)
`c` is a vector of the weights (unknown) that we are trying to approximate.
`d` is a vector of the epsilon values of the corresponding constraints.

2. approximate the weights using least squares.

3.  Once the weights are approximated, we can then get the scalar value of F(X) by replacing `cj` with `X`.

Is the above more or less correct?

Also, does the polynomial degree correspond to the number of weights?

**Comment by jpanetta** [comment]
Hopefully after today's recitation things have been clarified. It looks like you were confused by the slides on RBF interpolation, which is a different technique from the MLS interpolation the assignment uses.

The equations you describe in (1) are incorrect; the ones you want to solve are listed on slide 18 of the [second recitation slides](https://github.com/danielepanozzo/gp/raw/master/recitation_slides/section_2.pdf). Let me know if there's still a confusion.

**Comment by oveddan** [comment]
It was cleared up in the recitation today, thank you.
