### ISSUE TITLE
Assignment 4 Question 3 Gradient of function

### ISSUE THREAD

**Issue by txstc55** [danielepanozzo/gp-old#60]
it says: Compute the gradient of the selected mapping function and overlay it (key ’6’).

What does it mean to compute the gradient of a mapping function, I cannot find it in the slides anywhere. Are we supposed to define our own soft constraints or hard constraints then repeat problem 1 and 2?

**Comment by jiangzhongshi** [comment]
Hi,

the mapping function is a scalar field defined on the vertices and linear on the faces, the gradient of a scalar function on the mesh  can be found here https://cs.nyu.edu/~panozzo/gp/CotanLaplacian.pdf
