### ISSUE TITLE
Assignment 4. Task 1.2 Which object to use?

### ISSUE THREAD

**Issue by LihengGong** [danielepanozzo/gp-old#61]
Assignment 4. Task 1.2 Which object to use?

Dear professor,

Regarding task 1.2, I have several questions.

1. From handout, task 1.2 is to solve the following problem:
  Qu = 0 such that u|(cf) = c

And to solve this problem, based on issue discussion of 17 spring class, I kind of figure out that "Variable Elimination via Row/Col Removal" is the right tool.

My question is: is my understanding correct?

2. Regarding task 1.2, are we performing the calculation based on "bumpy.off" or other meshes in ./data directory?

3. Regarding constraints, are there any requirements for selecting the constraints? Or are we free to select any constraint as long as it makes sense(for example just select 1,1)?

**Comment by danielepanozzo** [comment]
1. Yes
2. You can use the mesh that you prefer
3. You are free to use any constraint that you want (but note that you must have at least one or the system will be undetermined)

**Comment by LihengGong** [comment]
Got it. Crystally clear. Thank you prof.
