### ISSUE TITLE
[Assignment 4]Gradient matrix G: is it computed directly from igl::grad ?

### ISSUE THREAD

**Issue by LihengGong** [danielepanozzo/gp-old#62]
[Assignment 4]Gradient matrix G: is it computed directly from `igl::grad`?

My understanding is that for task 2, the "gradient matrix" is essential for the following steps.
I read handout and slides carefully but couldn't find the method for deriving this "gardient matrix" `G`, but in libigl tutorial example 204_Gradient, I can see that there is an API called `igl::grad(V,F,G)`.

My question is: can we use this API directly to get "gradient matrix" G?

**Comment by danielepanozzo** [comment]
Yes you can use igl::grad to get the matrix G.

**Comment by LihengGong** [comment]
Thanks prof. Have a nice weekend.

Just curious, what materials should I refer to if I'm interested in how to derive this matrix?

**Comment by danielepanozzo** [comment]
The derivation is the last section of this slide set: https://cs.nyu.edu/~panozzo/gp/08%20-%20Single%20Patch%20Parametrization.pdf

Have a good weekend!

**Comment by LihengGong** [comment]
Got it. Thank you!
