### ISSUE TITLE
[project]how to use igl/triangle/triangulate.h?

### ISSUE THREAD

**Issue by peiyueY** [danielepanozzo/gp-old#66]
Hi,
I want to add **#include <igl/triangle/triangulate.h>**to use igl::triangle::triangulate(V, E, H, "a100.0.05qY", V2, F2) in my project. But the compiler complains **"fatal error: 'triangle.h' file not found"**. 

I try to annotate **"extern "C"{#include <triangle.h>}"** in triangulate.h but in that way I just get more errors...

So is there any way to use triangulate.h safely or is there any equivalent function that can replace igl::triangle::triangulate(V, E, H, "a100.0.05qY", V2, F2)?

**Comment by jiangzhongshi** [comment]
Hi,

My guess is that you are not linking to `igl::triangle` as in https://github.com/libigl/libigl/blob/master/tutorial/604_Triangle/CMakeLists.txt#L5

**Comment by peiyueY** [comment]
Thanks for your reply. But when I add igl::triangle as **target_link_libraries(${PROJECT_NAME}_bin igl::core igl::opengl igl::opengl_glfw igl::opengl_glfw_imgui igl::triangle)**, I get CMake Error: 
**CMake Error at CMakeLists.txt:42 (add_executable):
  Target "final_bin" links to target "igl::triangle" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?**

**Comment by jiangzhongshi** [comment]
Can you try also changing this line in the options:

```
option(LIBIGL_WITH_TRIANGLE "Use Triangle" ON)
```

**Comment by peiyueY** [comment]
Hi,
I have changed the line you listed but the problem is still unsolved. Can you take a look at my CMakeLists.txt file? I have sent to you through mail. Thanks.

**Comment by jiangzhongshi** [comment]
Your configuration seems fine. Can you remove the build folder, and external folder to try again?

**Comment by peiyueY** [comment]
Yes it works quite well now! Thanks for your help!
